# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tipos_documento_cargos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('obligatorio', models.BooleanField(default=False)),
                ('tiene_vencimiento', models.BooleanField(default=False)),
                ('dias_notificacion_vencimiento', models.IntegerField(default=30)),
                ('formatos_permitidos', models.CharField(default='PDF,JPG,PNG', max_length=100)),
                ('tamaño_maximo_mb', models.IntegerField(default=5)),
                ('requiere_aprobacion', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento de Empleado',
                'verbose_name_plural': 'Tipos de Documento de Empleado',
                'db_table': 'tipos_documento_empleado',
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('cargado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cargados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Empleado',
                'verbose_name_plural': 'Documentos de Empleado',
                'db_table': 'documentos_empleado',
            },
        ),
    ]
