# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('employees', '0001_initial'),
        ('organizational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='tipodocumentocargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.cargo'),
        ),
        migrations.AddField(
            model_name='tipodocumentocargo',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tipodocumentoempleado'),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.tipodocumentoempleado'),
        ),
        migrations.AlterUniqueTogether(
            name='documentoempleado',
            unique_together={('empleado', 'tipo_documento')},
        ),
    ]
