# Generated by Django 5.2.5 on 2026-08-27 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0046_empleado_fecha_retiro'),
        ('surveys', '0003_seed_tipos_encuesta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Identificador corto, p. ej. SORTEO-CEL-2026.', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, help_text='Foto del/los premios (celulares, computadores…).', null=True, upload_to='sorteos/')),
                ('cantidad_premios', models.PositiveIntegerField(default=1, help_text='Cuántas veces se puede sortear (nº de premios idénticos).')),
                ('require_pwa', models.BooleanField(default=True, help_text='Exige tener SIGHU instalada como PWA (o suscripción push activa).')),
                ('fecha_inicio_inscripcion', models.DateField()),
                ('fecha_fin_inscripcion', models.DateField()),
                ('fecha_sorteo', models.DateField()),
                ('activo', models.BooleanField(default=True, help_text='Los sorteos ya realizados se apagan aquí para archivarlos.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sorteos_creados', to=settings.AUTH_USER_MODEL)),
                ('encuesta_requisito', models.ForeignKey(help_text='El empleado debe haber COMPLETADO esta encuesta para inscribirse.', on_delete=django.db.models.deletion.PROTECT, related_name='sorteos_que_la_requieren', to='surveys.encuesta')),
            ],
            options={
                'verbose_name': 'Sorteo',
                'verbose_name_plural': 'Sorteos',
                'db_table': 'sorteos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionSorteo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(help_text='Número correlativo dentro del sorteo, empieza en 1.')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_sorteo', to='employees.empleado')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='sorteos.sorteo')),
            ],
            options={
                'verbose_name': 'Inscripción de sorteo',
                'verbose_name_plural': 'Inscripciones de sorteo',
                'db_table': 'sorteos_inscripcion',
                'ordering': ['sorteo', 'numero'],
                'unique_together': {('sorteo', 'empleado'), ('sorteo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GanadorSorteo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden_premio', models.PositiveIntegerField(help_text='1er premio extraído, 2do, ...')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('seleccionado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premios_sorteo_seleccionados', to=settings.AUTH_USER_MODEL)),
                ('inscripcion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ganador', to='sorteos.inscripcionsorteo')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ganadores', to='sorteos.sorteo')),
            ],
            options={
                'verbose_name': 'Ganador de sorteo',
                'verbose_name_plural': 'Ganadores de sorteo',
                'db_table': 'sorteos_ganador',
                'ordering': ['sorteo', 'orden_premio'],
                'unique_together': {('sorteo', 'orden_premio')},
            },
        ),
    ]
