# Generated by Django 5.2.5 on 2026-09-30 17:11

import apps.beneficios_retencion.models
import django.core.files.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0051_empleado_es_declarante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DependienteBeneficio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=200)),
                ('numero_documento', models.CharField(blank=True, max_length=30)),
                ('parentesco', models.CharField(blank=True, help_text="Descripción libre e informativa (ej: 'hijo', 'esposa').", max_length=50)),
                ('causal', models.CharField(choices=[('hijo_menor_18', 'Hijo menor de 18 años'), ('hijo_18_23_estudiando', 'Hijo 18-23 años estudiando'), ('hijo_mayor_23_dependiente', 'Hijo mayor de 23 dependiente'), ('conyuge_dependiente', 'Cónyuge/compañero dependiente'), ('familiar_dependiente', 'Padres o hermanos dependientes')], help_text='Define qué documento se exige.', max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dependiente',
                'verbose_name_plural': 'Dependientes',
                'db_table': 'beneficios_retencion_dependiente',
            },
        ),
        migrations.CreateModel(
            name='SoporteDependiente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.beneficios_retencion.models._soporte_dependiente_upload_path)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('dependiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='beneficios_retencion.dependientebeneficio')),
            ],
            options={
                'verbose_name': 'Soporte de dependiente',
                'verbose_name_plural': 'Soportes de dependientes',
                'db_table': 'beneficios_retencion_soporte_dependiente',
            },
        ),
        migrations.CreateModel(
            name='TramiteBeneficio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('intereses_vivienda', 'Intereses de vivienda'), ('medicina_prepagada', 'Medicina prepagada'), ('dependientes', 'Dependientes'), ('aportes_voluntarios_pension', 'Aportes voluntarios a pensión'), ('afc', 'AFC (Ahorro para el Fomento a la Construcción)')], max_length=40)),
                ('anio_aplicacion', models.PositiveIntegerField(help_text='Año de nómina en el que aplica el beneficio.')),
                ('periodo_certificado', models.PositiveIntegerField(help_text='Año que reporta el documento. Vivienda/medicina = anio_aplicacion - 1. Dependientes = mismo anio_aplicacion.')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='En pesos, tal como está en el soporte. Sin topes. Opcional en dependientes.', max_digits=14, null=True)),
                ('periodicidad', models.CharField(blank=True, choices=[('anual', 'Anual'), ('mensual', 'Mensual')], help_text='Cómo leer `valor`. Vacío en dependientes.', max_length=10)),
                ('observacion_empleado', models.TextField(blank=True, help_text='Texto libre que el empleado agrega al cargar el trámite.')),
                ('estado', models.CharField(choices=[('pendiente_rrhh', 'Pendiente de revisión de RRHH'), ('validado', 'Validado por RRHH'), ('rechazado', 'Rechazado'), ('revocado', 'Revocado'), ('error_envio_odoo', 'Error al enviar a Odoo (reintentar)')], default='pendiente_rrhh', max_length=30)),
                ('observacion_rrhh', models.TextField(blank=True, help_text='Motivo del rechazo o comentario de validación de RRHH.')),
                ('validado_el', models.DateField(blank=True, help_text='Fecha en que RRHH validó o rechazó el trámite.', null=True)),
                ('odoo_id', models.PositiveIntegerField(blank=True, help_text='ID que devuelve Odoo tras registrar el trámite.', null=True)),
                ('aplica_desde', models.DateField(blank=True, help_text='Primera nómina afectada (según Odoo).', null=True)),
                ('vence_el', models.DateField(blank=True, help_text='Último día de vigencia (según Odoo, típicamente 30/04/N+1).', null=True)),
                ('respuesta_odoo', models.JSONField(blank=True, help_text='Última respuesta cruda de Odoo, para auditoría.', null=True)),
                ('ultimo_error_odoo', models.TextField(blank=True, help_text='Detalle del último error al llamar a Odoo, si hubo.')),
                ('enviado_a_odoo_el', models.DateTimeField(blank=True, help_text='Fecha/hora del último envío exitoso a Odoo.', null=True)),
                ('carta_generada_el', models.DateTimeField(blank=True, help_text='Fecha/hora en que se generó la carta juramentada por primera vez.', null=True)),
                ('carta_firmada', models.BooleanField(default=False, help_text='RRHH marca esto cuando el empleado firmó físicamente la carta.')),
                ('carta_firmada_el', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites_beneficio_retencion', to='employees.empleado')),
                ('validado_por', models.ForeignKey(blank=True, help_text='Usuario RRHH que validó o rechazó el trámite.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_validados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trámite de beneficio de retención',
                'verbose_name_plural': 'Trámites de beneficios de retención',
                'db_table': 'beneficios_retencion_tramite',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SoporteBeneficio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.beneficios_retencion.models._soporte_upload_path)),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soportes', to='beneficios_retencion.tramitebeneficio')),
            ],
            options={
                'verbose_name': 'Soporte de beneficio',
                'verbose_name_plural': 'Soportes de beneficios',
                'db_table': 'beneficios_retencion_soporte',
            },
        ),
        migrations.AddField(
            model_name='dependientebeneficio',
            name='tramite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependientes', to='beneficios_retencion.tramitebeneficio'),
        ),
        migrations.AddIndex(
            model_name='tramitebeneficio',
            index=models.Index(fields=['empleado', 'anio_aplicacion'], name='beneficios__emplead_b45616_idx'),
        ),
        migrations.AddIndex(
            model_name='tramitebeneficio',
            index=models.Index(fields=['estado'], name='beneficios__estado_3c1318_idx'),
        ),
    ]
