# Generated by Django 5.2.5 on 2026-10-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios_retencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitebeneficio',
            name='tipo',
            field=models.CharField(choices=[('intereses_vivienda', 'Intereses de vivienda'), ('medicina_prepagada', 'Medicina prepagada'), ('dependientes', 'Dependientes')], max_length=40),
        ),
    ]
