# Generated by Django 5.2.5 on 2026-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficios_retencion', '0002_alter_tramitebeneficio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramitebeneficio',
            name='estado',
            field=models.CharField(choices=[('pendiente_rrhh', 'Pendiente de revisión de RRHH'), ('validado', 'Validado por RRHH'), ('rechazado', 'Rechazado'), ('revocado', 'Revocado')], default='pendiente_rrhh', max_length=30),
        ),
    ]
