# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Capacitación',
                'verbose_name_plural': 'Tipos de Capacitación',
                'db_table': 'tipos_capacitacion',
            },
        ),
        migrations.CreateModel(
            name='TipoContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('extensiones_permitidas', models.CharField(max_length=100)),
                ('mime_types', models.CharField(max_length=200)),
                ('requiere_archivo', models.BooleanField(default=True)),
                ('requiere_url', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tipo de Contenido',
                'verbose_name_plural': 'Tipos de Contenido',
                'db_table': 'tipos_contenido',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_estimada_horas', models.IntegerField()),
                ('puntaje_aprobacion', models.IntegerField(default=70)),
                ('intentos_maximos', models.IntegerField(default=3)),
                ('fecha_vigencia_inicio', models.DateField()),
                ('fecha_vigencia_fin', models.DateField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.tipocapacitacion')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
                'db_table': 'capacitaciones',
                'unique_together': {('codigo', 'version')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionCapacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('vencido', 'Vencido')], default='no_iniciado', max_length=25)),
                ('obligatoria', models.BooleanField()),
                ('aprobada_supervisor', models.BooleanField(default=True)),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tiempo_total_minutos', models.IntegerField(default=0)),
                ('intentos_realizados', models.IntegerField(default=0)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.capacitacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('inscrito_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscripción a Capacitación',
                'verbose_name_plural': 'Inscripciones a Capacitación',
                'db_table': 'inscripciones_capacitacion',
                'unique_together': {('empleado', 'capacitacion')},
            },
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField()),
                ('duracion_estimada_minutos', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('leccion_prerequisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.leccion')),
            ],
            options={
                'verbose_name': 'Lección',
                'verbose_name_plural': 'Lecciones',
                'db_table': 'lecciones',
            },
        ),
        migrations.CreateModel(
            name='ContenidoLeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, upload_to='capacitaciones/')),
                ('url_externa', models.URLField(blank=True)),
                ('orden', models.IntegerField()),
                ('obligatorio', models.BooleanField(default=True)),
                ('tiempo_minimo_visualizacion', models.IntegerField(default=0)),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.leccion')),
                ('tipo_contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.tipocontenido')),
            ],
            options={
                'verbose_name': 'Contenido de Lección',
                'verbose_name_plural': 'Contenidos de Lección',
                'db_table': 'contenidos_leccion',
                'unique_together': {('leccion', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='ModuloCapacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.IntegerField()),
                ('duracion_estimada_minutos', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.capacitacion')),
                ('modulo_prerequisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.modulocapacitacion')),
            ],
            options={
                'verbose_name': 'Módulo de Capacitación',
                'verbose_name_plural': 'Módulos de Capacitación',
                'db_table': 'modulos_capacitacion',
                'unique_together': {('capacitacion', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='leccion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.modulocapacitacion'),
        ),
        migrations.CreateModel(
            name='CapacitacionCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoria', models.BooleanField(default=True)),
                ('dias_plazo_completar', models.IntegerField(default=30)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.capacitacion')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.cargo')),
            ],
            options={
                'db_table': 'capacitaciones_cargos',
                'unique_together': {('capacitacion', 'cargo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='leccion',
            unique_together={('modulo', 'orden')},
        ),
        migrations.CreateModel(
            name='ProgresoCapacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completado', models.BooleanField(default=False)),
                ('tiempo_dedicado_segundos', models.IntegerField(default=0)),
                ('porcentaje_visto', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('numero_visitas', models.IntegerField(default=0)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.contenidoleccion')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.inscripcioncapacitacion')),
            ],
            options={
                'verbose_name': 'Progreso de Capacitación',
                'verbose_name_plural': 'Progresos de Capacitación',
                'db_table': 'progreso_capacitacion',
                'unique_together': {('inscripcion', 'contenido')},
            },
        ),
    ]
