# Generated by Django 5.2 on 2025-07-28 13:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('sitio_web', models.URLField(blank=True)),
                ('contacto_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor Externo',
                'verbose_name_plural': 'Proveedores Externos',
                'db_table': 'proveedores_externos',
            },
        ),
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Capacitación', 'verbose_name_plural': 'Capacitaciones'},
        ),
        migrations.AlterModelOptions(
            name='capacitacioncargo',
            options={'verbose_name': 'Capacitación por Cargo', 'verbose_name_plural': 'Capacitaciones por Cargo'},
        ),
        migrations.AlterModelOptions(
            name='contenidoleccion',
            options={'ordering': ['leccion', 'orden'], 'verbose_name': 'Contenido de Lección', 'verbose_name_plural': 'Contenidos de Lección'},
        ),
        migrations.AlterModelOptions(
            name='inscripcioncapacitacion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name': 'Inscripción a Capacitación', 'verbose_name_plural': 'Inscripciones a Capacitación'},
        ),
        migrations.AlterModelOptions(
            name='leccion',
            options={'ordering': ['modulo', 'orden'], 'verbose_name': 'Lección', 'verbose_name_plural': 'Lecciones'},
        ),
        migrations.AlterModelOptions(
            name='modulocapacitacion',
            options={'ordering': ['capacitacion', 'orden'], 'verbose_name': 'Módulo de Capacitación', 'verbose_name_plural': 'Módulos de Capacitación'},
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo en pesos colombianos', max_digits=10),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='nivel_dificultad',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='permite_autocompletado',
            field=models.BooleanField(default=False, help_text='El empleado puede marcar como completada sin evaluación'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='permite_certificacion_manual',
            field=models.BooleanField(default=True, help_text='Permite que administrador certifique manualmente'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='puntos_gamificacion',
            field=models.IntegerField(default=0, help_text='Puntos que otorga al completar', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='requiere_certificado_externo',
            field=models.BooleanField(default=False, help_text='Requiere subir certificado del proveedor al finalizar'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='requiere_prerequisitos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='url_inscripcion_externa',
            field=models.URLField(blank=True, help_text='URL para inscripción directa en el proveedor'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='visible_en_catalogo',
            field=models.BooleanField(default=True, help_text='Visible en catálogo para empleados'),
        ),
        migrations.AddField(
            model_name='capacitacioncargo',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='capacitacioncargo',
            name='prioridad',
            field=models.IntegerField(default=1, help_text='1=Alta, 2=Media, 3=Baja', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='contenidoleccion',
            name='contenido_texto',
            field=models.TextField(blank=True, help_text='Para contenido de texto directo'),
        ),
        migrations.AddField(
            model_name='contenidoleccion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contenidoleccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-28 08:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contenidoleccion',
            name='permite_descarga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contenidoleccion',
            name='tamaño_archivo_mb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='certificado_externo',
            field=models.FileField(blank=True, help_text='Certificado obtenido del proveedor externo', upload_to='capacitaciones/certificados/'),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='fecha_certificado_externo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='observaciones_admin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='observaciones_empleado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='observaciones_supervisor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='porcentaje_completado',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='validado_por_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-28 08:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leccion',
            name='requiere_completar_anterior',
            field=models.BooleanField(default=True, help_text='Debe completar la lección anterior para acceder'),
        ),
        migrations.AddField(
            model_name='leccion',
            name='tiempo_minimo_visualizacion',
            field=models.IntegerField(default=0, help_text='Tiempo mínimo en segundos que debe ver la lección'),
        ),
        migrations.AddField(
            model_name='modulocapacitacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modulocapacitacion',
            name='permite_repetir',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modulocapacitacion',
            name='puntaje_minimo_aprobar',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='progresocapacitacion',
            name='fecha_ultimo_acceso',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='progresocapacitacion',
            name='marcadores',
            field=models.JSONField(blank=True, default=list, help_text='Marcadores de tiempo en videos'),
        ),
        migrations.AddField(
            model_name='progresocapacitacion',
            name='notas_empleado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='progresocapacitacion',
            name='puntuacion_contenido',
            field=models.IntegerField(blank=True, help_text='Puntuación de 1 a 5 del empleado', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='progresocapacitacion',
            name='tiempo_promedio_por_visita',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipocapacitacion',
            name='permite_inscripcion_libre',
            field=models.BooleanField(default=False, help_text='Permite autogestión por empleados'),
        ),
        migrations.AddField(
            model_name='tipocapacitacion',
            name='requiere_aprobacion_supervisor',
            field=models.BooleanField(default=False, help_text='Requiere aprobación del supervisor'),
        ),
        migrations.AddField(
            model_name='tipocontenido',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipocontenido',
            name='color_hex',
            field=models.CharField(default='#6c757d', help_text='Color hexadecimal', max_length=7),
        ),
        migrations.AddField(
            model_name='tipocontenido',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tipocontenido',
            name='icono_fa',
            field=models.CharField(default='fas fa-file', help_text='Clase de FontAwesome', max_length=50),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='duracion_estimada_horas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='intentos_maximos',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='puntaje_aprobacion',
            field=models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='capacitacioncargo',
            name='dias_plazo_completar',
            field=models.IntegerField(default=30, help_text='Días que tiene el empleado para completar desde la asignación'),
        ),
        migrations.AlterField(
            model_name='contenidoleccion',
            name='archivo',
            field=models.FileField(blank=True, upload_to='capacitaciones/contenido/'),
        ),
        migrations.AlterField(
            model_name='contenidoleccion',
            name='tiempo_minimo_visualizacion',
            field=models.IntegerField(default=0, help_text='Tiempo mínimo en segundos'),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='estado',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='no_iniciado', max_length=25),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='inscrito_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modulocapacitacion',
            name='modulo_prerequisito',
            field=models.ForeignKey(blank=True, help_text='Módulo que debe completarse antes de este', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.modulocapacitacion'),
        ),
        migrations.AlterField(
            model_name='progresocapacitacion',
            name='porcentaje_visto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tipocontenido',
            name='extensiones_permitidas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tipocontenido',
            name='mime_types',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='proveedor_externo',
            field=models.ForeignKey(blank=True, help_text='Solo para capacitaciones externas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.proveedorexterno'),
        ),
        migrations.CreateModel(
            name='CapacitacionPrerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatorio', models.BooleanField(default=True, help_text='Si es falso, es solo recomendado')),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos', to='training.capacitacion')),
                ('capacitacion_prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_prerequisito_de', to='training.capacitacion')),
            ],
            options={
                'verbose_name': 'Prerequisito de Capacitación',
                'verbose_name_plural': 'Prerequisitos de Capacitación',
                'db_table': 'capacitaciones_prerequisitos',
                'unique_together': {('capacitacion', 'capacitacion_prerequisito')},
            },
        ),
    ]
