# Generated by Django 5.2 on 2025-08-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_proveedorexterno_alter_capacitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='activa',
            field=models.BooleanField(default=True, help_text='Indica si la capacitación está disponible para inscripción'),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='estado',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('pendiente_validacion', 'Pendiente de Validación'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='no_iniciado', max_length=25),
        ),
    ]
