# Generated by Django 5.2 on 2025-08-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_capacitacion_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='obligatoria',
            field=models.BooleanField(default=False),
        ),
    ]
