# Generated by Django 5.2 on 2025-08-20 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_inscripcioncapacitacion_obligatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='leccion_prerequisito',
            field=models.ForeignKey(blank=True, help_text='Lección que debe completarse antes de esta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.leccion'),
        ),
    ]
