# Generated by Django 5.2 on 2025-08-21 12:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_add_prerequisitos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('multiple', 'Selección Múltiple'), ('verdadero_falso', 'Verdadero/Falso')], default='multiple', max_length=20)),
                ('puntaje', models.PositiveIntegerField(default=1)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='evaluaciones/preguntas/')),
                ('explicacion', models.TextField(blank=True, help_text='Explicación que se mostrará después de responder')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta de Quiz',
                'verbose_name_plural': 'Preguntas de Quiz',
                'db_table': 'training_preguntas_quiz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionPreguntaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('retroalimentacion', models.TextField(blank=True, help_text='Retroalimentación específica para esta opción')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='training.preguntaquiz')),
            ],
            options={
                'verbose_name': 'Opción de Quiz',
                'verbose_name_plural': 'Opciones de Quiz',
                'db_table': 'training_opciones_quiz',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='QuizLeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('porcentaje_aprobacion', models.PositiveIntegerField(default=70, help_text='Porcentaje mínimo para aprobar', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('tiempo_limite', models.PositiveIntegerField(blank=True, help_text='Tiempo límite en minutos. Dejar en blanco si no hay límite', null=True)),
                ('intentos_maximos', models.PositiveIntegerField(default=3, help_text='Número máximo de intentos permitidos. 0 para intentos ilimitados')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('leccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='training.leccion')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'db_table': 'training_evaluaciones',
            },
        ),
        migrations.AddField(
            model_name='preguntaquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='training.quizleccion'),
        ),
        migrations.CreateModel(
            name='IntentoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tiempo_utilizado', models.PositiveIntegerField(help_text='Tiempo utilizado en segundos', null=True)),
                ('aprobado', models.BooleanField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_quiz', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='training.quizleccion')),
            ],
            options={
                'verbose_name': 'Intento de Quiz',
                'verbose_name_plural': 'Intentos de Quiz',
                'db_table': 'training_intentos_quiz',
            },
        ),
        migrations.CreateModel(
            name='RespuestaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='training.intentoquiz')),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='training.opcionpreguntaquiz')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.preguntaquiz')),
            ],
            options={
                'verbose_name': 'Respuesta de Quiz',
                'verbose_name_plural': 'Respuestas de Quiz',
                'db_table': 'training_respuestas_quiz',
            },
        ),
    ]
