# Generated by Django 5.2.5 on 2025-08-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_add_quiz_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontenido',
            name='codigo',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
