# Generated by Django 5.2.5 on 2025-11-12 13:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_tipocontenido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidoleccion',
            name='archivo',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='capacitaciones/contenido/'),
        ),
        migrations.AlterField(
            model_name='preguntaquiz',
            name='imagen',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='evaluaciones/preguntas/'),
        ),
    ]
