# Generated by Django 5.2.5 on 2025-12-18 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_contenidoleccion_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='es_capacitacion_externa',
            field=models.BooleanField(default=False, help_text='Marcar si es ofrecida por un proveedor externo', verbose_name='Es capacitación externa'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='nombre_proveedor',
            field=models.CharField(blank=True, help_text='Nombre del proveedor externo (ej: Coursera, Udemy, LinkedIn Learning)', max_length=200, verbose_name='Nombre del proveedor'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='url_curso_externo',
            field=models.URLField(blank=True, help_text='URL donde el empleado puede ver el contenido del curso externo', verbose_name='URL del curso externo'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='proveedor_externo',
            field=models.ForeignKey(blank=True, help_text='(Obsoleto) Solo para capacitaciones externas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.proveedorexterno'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='requiere_certificado_externo',
            field=models.BooleanField(default=True, help_text='El empleado debe presentar certificado de aprobación', verbose_name='Requiere certificado'),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='url_inscripcion_externa',
            field=models.URLField(blank=True, help_text='(Obsoleto) URL para inscripción directa en el proveedor'),
        ),
    ]
