# Generated by Django 5.2.5 on 2026-02-06 22:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_capacitacion_es_capacitacion_externa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='certificado_generado',
            field=models.FileField(blank=True, help_text='Certificado PDF generado automáticamente por el sistema', null=True, upload_to='capacitaciones/certificados_generados/'),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='fecha_emision_certificado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se emitió el certificado', null=True),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='numero_certificado',
            field=models.CharField(blank=True, help_text='Identificador único del certificado (ej: CERT-2025-001)', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CertificadoPlantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_certificado', models.CharField(default='Certificado de Capacitación', help_text='Título principal del certificado', max_length=200)),
                ('texto_superior', models.TextField(default='Se certifica que', help_text='Texto que aparece antes del nombre del empleado')),
                ('texto_inferior', models.TextField(default='Ha completado satisfactoriamente la capacitación', help_text='Texto que aparece después del nombre del empleado')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la empresa (opcional)', null=True, upload_to='certificados/logos/')),
                ('firma_responsable', models.ImageField(blank=True, help_text='Imagen de la firma del responsable (opcional)', null=True, upload_to='certificados/firmas/')),
                ('nombre_responsable', models.CharField(blank=True, help_text='Nombre de quien firma el certificado', max_length=200)),
                ('cargo_responsable', models.CharField(blank=True, help_text='Cargo de quien firma el certificado', max_length=200)),
                ('incluir_calificacion', models.BooleanField(default=True, help_text='Mostrar la calificación en el certificado')),
                ('incluir_duracion', models.BooleanField(default=True, help_text='Mostrar la duración de la capacitación')),
                ('nota_minima_certificado', models.DecimalField(decimal_places=2, default=70.0, help_text='Nota mínima para generar el certificado automáticamente', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.OneToOneField(help_text='Capacitación a la que pertenece esta plantilla', on_delete=django.db.models.deletion.CASCADE, related_name='plantilla_certificado', to='training.capacitacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantillas_certificados_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Certificado',
                'verbose_name_plural': 'Plantillas de Certificados',
                'db_table': 'certificados_plantillas',
            },
        ),
    ]
