# Generated by Django 5.2.5 on 2026-02-09 13:56

import apps.training.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_inscripcioncapacitacion_certificado_generado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='firma_responsable',
            field=models.ImageField(blank=True, help_text='Imagen de la firma del responsable (opcional)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.training.utils.get_plantilla_firma_upload_path),
        ),
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa (opcional)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.training.utils.get_plantilla_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='certificado_externo',
            field=models.FileField(blank=True, help_text='Certificado obtenido del proveedor externo', storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.training.utils.get_certificado_externo_upload_path),
        ),
        migrations.AlterField(
            model_name='inscripcioncapacitacion',
            name='certificado_generado',
            field=models.FileField(blank=True, help_text='Certificado PDF generado automáticamente por el sistema', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.training.utils.get_certificado_generado_upload_path),
        ),
    ]
