# Generated by Django 5.2.5 on 2026-02-09 16:02

import apps.training.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_certificadoplantilla_firma_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoplantilla',
            name='cargo_rrhh',
            field=models.CharField(blank=True, default='Director de Recursos Humanos', help_text='Cargo del responsable de RRHH', max_length=200),
        ),
        migrations.AddField(
            model_name='certificadoplantilla',
            name='firma_rrhh',
            field=models.ImageField(blank=True, help_text='Imagen de la firma del Director de RRHH (opcional)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.training.utils.get_plantilla_firma_rrhh_upload_path),
        ),
        migrations.AddField(
            model_name='certificadoplantilla',
            name='nombre_rrhh',
            field=models.CharField(blank=True, default='Director de Recursos Humanos', help_text='Nombre del Director de RRHH', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='cargo_responsable',
            field=models.CharField(blank=True, help_text='Cargo de quien firma el certificado (creador de la capacitación)', max_length=200),
        ),
    ]
