# Generated by Django 5.0.3

from django.db import migrations, models
import apps.training.utils
import custom_storage.media


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_certificadoplantilla_cargo_rrhh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificadoplantilla',
            name='imagen_fondo',
            field=models.ImageField(
                blank=True,
                help_text='Imagen de fondo decorativa con arabescos/marcos ornamentales (opcional)',
                null=True,
                storage=custom_storage.media.MediaStorage(),
                upload_to=apps.training.utils.get_plantilla_fondo_upload_path
            ),
        ),
    ]
