# Generated by Django 5.2.5 on 2026-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_certificadoplantilla_imagen_fondo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='texto_inferior',
            field=models.TextField(default='Ha completado satisfactoriamente la capacitación en: , la cual se dio de forma virtual por medio de la plataforma de SIGHU', help_text='Texto que aparece después del nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='texto_superior',
            field=models.TextField(default='Certifica que ', help_text='Texto que aparece antes del nombre del empleado'),
        ),
        migrations.AlterField(
            model_name='certificadoplantilla',
            name='titulo_certificado',
            field=models.CharField(default='El Area de: ', help_text='Título principal del certificado', max_length=200),
        ),
    ]
