# Generated by Django 5.2.5 on 2026-06-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_certificadoplantilla_texto_inferior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='emite_certificado',
            field=models.BooleanField(default=True, help_text='Si está activo, al aprobar el curso se genera el PDF de certificado automáticamente. Para capacitaciones obligatorias o de inducción se suele desactivar; actívalo manualmente cuando sí se requiera evidencia (SST, compliance, etc.).', verbose_name='Emite certificado al aprobar'),
        ),
    ]
