# Generated by Django 5.2.5 on 2026-08-03 15:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_novedades_nomina'),
        ('training', '0016_seed_emite_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCapacitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código único de la convocatoria (ej: SST-2026-SEP).', max_length=40)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('mixta', 'Mixta (presencial + online)')], default='presencial', max_length=15)),
                ('lugar', models.CharField(help_text='Aula, sede o sala virtual (ej: Aula planta Caldas).', max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('cupo_maximo', models.PositiveIntegerField(blank=True, help_text='Cupo máximo de inscritos. Null = ilimitado.', null=True)),
                ('inscripcion_abierta', models.BooleanField(default=False, help_text='Si está marcado, los empleados pueden auto-inscribirse desde el catálogo.')),
                ('ventana_inscripcion_desde', models.DateField(blank=True, null=True)),
                ('ventana_inscripcion_hasta', models.DateField(blank=True, null=True)),
                ('porcentaje_asistencia_minimo', models.PositiveIntegerField(default=80, help_text='% mínimo de días asistidos para aprobar y recibir certificado.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='programada', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.ForeignKey(help_text='Capacitación (contenido) que se dicta en esta sesión.', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='training.capacitacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('encargado', models.ForeignKey(help_text='Empleado responsable de dictar y tomar asistencia.', on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_a_cargo', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Sesión de capacitación',
                'verbose_name_plural': 'Sesiones de capacitación',
                'db_table': 'training_sesiones_capacitacion',
                'ordering': ['-fecha_inicio', 'codigo'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncapacitacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscripcioncapacitacion',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Convocatoria/sesión presencial específica a la que pertenece esta inscripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones', to='training.sesioncapacitacion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcioncapacitacion',
            unique_together={('empleado', 'capacitacion', 'sesion')},
        ),
        migrations.CreateModel(
            name='AsistenciaSesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField(help_text='Día concreto de la sesión.')),
                ('asistio', models.BooleanField(default=False)),
                ('hora_llegada', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_sesion', to='training.inscripcioncapacitacion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_sesion_registradas', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Asistencia a sesión',
                'verbose_name_plural': 'Asistencias a sesiones',
                'db_table': 'training_asistencia_sesion',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['inscripcion', 'fecha'], name='training_as_inscrip_0ff14b_idx')],
                'constraints': [models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='unique_asistencia_inscripcion_fecha')],
            },
        ),
        migrations.AddIndex(
            model_name='sesioncapacitacion',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='training_se_estado_883c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='sesioncapacitacion',
            index=models.Index(fields=['encargado', '-fecha_inicio'], name='training_se_encarga_44b24e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sesioncapacitacion',
            constraint=models.UniqueConstraint(fields=('capacitacion', 'codigo'), name='unique_capacitacion_codigo_sesion'),
        ),
    ]
