# Generated by Django 5.2.5 on 2026-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_sesiones_capacitacion_presencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='modalidad',
            field=models.CharField(choices=[('online', 'Online / Autoservicio'), ('presencial', 'Presencial'), ('mixta', 'Mixta (presencial + online)')], default='online', help_text='Presencial: se dicta en aula/sitio en una fecha programada (sesiones). Online: contenido en la plataforma. Mixta: combina ambas.', max_length=15),
        ),
    ]
