# Generated by Django 5.2.5 on 2026-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_capacitacion_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='url_reunion',
            field=models.URLField(blank=True, help_text='URL de Meet, Zoom o similar para empleados que no puedan asistir presencialmente. Aplica a todas las sesiones de este curso.', verbose_name='Link de asistencia virtual (opcional)'),
        ),
    ]
