# Generated by Django 5.2.5 on 2026-06-25 16:43

import apps.core.models
import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_logactividad_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCorporativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Resumen breve del contenido del documento')),
                ('categoria', models.CharField(choices=[('reglamento', 'Reglamentos'), ('politica', 'Políticas'), ('manual', 'Manuales'), ('procedimiento', 'Procedimientos'), ('formato', 'Formatos'), ('otro', 'Otros')], default='reglamento', max_length=20)),
                ('archivo', models.FileField(help_text='PDF, DOCX o imagen', max_length=500, storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.core.models._documento_corporativo_upload_path)),
                ('version', models.CharField(blank=True, help_text='Ej: v1.0, 2026, etc.', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vigencia_desde', models.DateField(blank=True, null=True)),
                ('fecha_vigencia_hasta', models.DateField(blank=True, help_text='Opcional, si el documento tiene vencimiento', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si está activo, aparece en la sección de documentos del empleado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_corporativos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Corporativo',
                'verbose_name_plural': 'Documentos Corporativos',
                'db_table': 'documentos_corporativos',
                'ordering': ['categoria', '-fecha_publicacion'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='documentos__activo_474c6e_idx')],
            },
        ),
    ]
