# Generated by Django 5.2 on 2025-07-24 15:30

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempleado',
            name='archivo',
            field=models.FileField(upload_to=apps.documents.models.get_upload_path),
        ),
    ]
