# Generated by Django 5.2 on 2025-08-20 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documentoempleado_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoempleado',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentoempleado',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
