# Generated by Django 5.2.5 on 2025-11-12 13:30

import apps.documents.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_documentoempleado_fecha_rechazo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoempleado',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=apps.documents.models.get_upload_path),
        ),
    ]
