# Generated by Django 5.2 on 2025-07-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('organizational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='rol_automatico',
            field=models.ForeignKey(blank=True, help_text='Rol que se asigna automáticamente a empleados con este cargo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.rol', verbose_name='Rol del Sistema'),
        ),
    ]
