# Generated by Django 5.2.5 on 2026-06-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0002_cargo_rol_automatico'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_analitica', models.CharField(help_text='Cuenta analítica contable (único)', max_length=30, unique=True)),
                ('referencia', models.CharField(blank=True, help_text='Referencia interna corta', max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sede', models.ForeignKey(help_text='Centro de operaciones (sede)', on_delete=django.db.models.deletion.PROTECT, related_name='centros_costo', to='organizational.sede')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'db_table': 'centros_costo',
                'ordering': ['cuenta_analitica'],
            },
        ),
    ]
