# Generated by Django 5.2.5 on 2026-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0003_centrocosto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centrocosto',
            options={'ordering': ['referencia'], 'verbose_name': 'Centro de Costo', 'verbose_name_plural': 'Centros de Costo'},
        ),
        migrations.RemoveField(
            model_name='centrocosto',
            name='sede',
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='cuenta_analitica',
            field=models.CharField(help_text='Etiqueta Odoo: [CODE] NOMBRE', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='referencia',
            field=models.CharField(blank=True, help_text='Código corto de referencia (ej: 1001)', max_length=30),
        ),
    ]
