# Generated by Django 5.2.5 on 2026-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0005_seed_centros_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='crea_usuario_sistema',
            field=models.BooleanField(default=True, help_text='Si está marcado, al asignar este cargo a un empleado nuevo se crea su usuario automáticamente. Desmarca para cargos sin acceso al sistema (ej: aprendiz en etapa lectiva). El usuario se creará cuando el empleado pase a un cargo que sí lo permita.', verbose_name='¿Crea usuario en el sistema?'),
        ),
    ]
