# Generated by Django 5.2.5 on 2026-08-11 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0006_agregar_crea_usuario_sistema_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='es_cargo_aprendiz',
            field=models.BooleanField(default=False, help_text='Marca este cargo si corresponde a un aprendiz del SENA (etapa lectiva o productiva). Los empleados con este cargo cuentan para la cuota de aprendices definida en la resolución vigente del SENA.', verbose_name='¿Es cargo de aprendiz SENA?'),
        ),
        migrations.CreateModel(
            name='ResolucionSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de resolución (ej: 1-0001-2026-0007890)', max_length=60)),
                ('fecha_expedicion', models.DateField(help_text='Fecha en que el SENA expidió la resolución.')),
                ('fecha_vigencia_inicio', models.DateField(help_text='Inicio de vigencia de esta cuota.')),
                ('fecha_vigencia_fin', models.DateField(blank=True, help_text='Fin de vigencia. Dejar vacío si aún no se conoce (se aplica hasta que llegue una nueva).', null=True)),
                ('cuota_aprendices', models.PositiveIntegerField(help_text='Cantidad total de aprendices que la empresa debe mantener según la resolución.')),
                ('total_trabajadores_base', models.PositiveIntegerField(blank=True, help_text='Total de trabajadores que consideró el SENA al calcular la cuota (informativo).', null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF oficial de la resolución (opcional pero recomendado).', null=True, upload_to='resoluciones_sena/')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones_sena_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resolución SENA',
                'verbose_name_plural': 'Resoluciones SENA',
                'db_table': 'resoluciones_sena',
                'ordering': ['-fecha_vigencia_inicio', '-fecha_expedicion'],
                'indexes': [models.Index(fields=['-fecha_vigencia_inicio'], name='resolucione_fecha_v_fec5ee_idx')],
            },
        ),
    ]
