# Generated by Django 5.2.5 on 2026-08-11 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0008_marcar_cargos_aprendiz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioMinimoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Año al que aplica este SMMLV (ej: 2026).', unique=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor mensual del SMMLV en pesos (ej: 1423500.00 para 2026).', max_digits=12)),
                ('decreto', models.CharField(blank=True, help_text='Número de decreto/norma que lo fija (ej: Decreto 1435 de 2025).', max_length=60)),
                ('fecha_expedicion', models.DateField(blank=True, help_text='Fecha del decreto (opcional).', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smmlv_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salario mínimo anual (SMMLV)',
                'verbose_name_plural': 'Salarios mínimos anuales (SMMLV)',
                'db_table': 'salario_minimo_anual',
                'ordering': ['-year'],
            },
        ),
    ]
