# Generated by Django 5.2.5 on 2026-08-12 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0010_seed_smmlv_2026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoReemplazosSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conseguidos', models.PositiveIntegerField(default=0, help_text='Cantidad de aprendices candidatos ya identificados/en proceso de contratación.')),
                ('notas', models.TextField(blank=True, help_text='Notas internas (nombres candidatos, estatus con SENA, etc.).')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos_sena_actualizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento reemplazos SENA',
                'verbose_name_plural': 'Seguimientos reemplazos SENA',
                'db_table': 'seguimiento_reemplazos_sena',
            },
        ),
    ]
