# Generated by Django 5.2.5 on 2026-08-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0011_seguimiento_reemplazos_sena'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='excluido_control_asistencia',
            field=models.BooleanField(default=False, help_text='Marca este cargo para excluir a sus ocupantes del módulo de asistencia: no aparecen como subordinados a los que se les registra asistencia, y si el cargo es jefe/gerente, no se le muestra el tablero para registrar la de otros (típico en gerente y directores).', verbose_name='¿Excluido del control de asistencia?'),
        ),
    ]
