# Generated by Django 5.2.5 on 2026-08-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizational', '0013_marcar_cargos_excluidos_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='excluido_gestion_asistencia',
            field=models.BooleanField(default=False, help_text='Los ocupantes NO ven el módulo para registrar la asistencia de otros ni reciben recordatorios ni se les mide cumplimiento (típico en gerente). Los directores usualmente NO tienen este flag: siguen registrando la asistencia de su equipo aunque a ellos no se les controle.', verbose_name='¿No gestiona asistencia de otros?'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='excluido_control_asistencia',
            field=models.BooleanField(default=False, help_text='Los ocupantes de este cargo NO aparecen como subordinados a los que se les registra asistencia (típico en gerente y directores).', verbose_name='¿No se le registra asistencia?'),
        ),
    ]
