# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puntos_base', models.IntegerField()),
                ('multiplicador_complejidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Actividad',
                'verbose_name_plural': 'Tipos de Actividad',
                'db_table': 'tipos_actividad',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('costo_puntos', models.IntegerField()),
                ('stock_inicial', models.IntegerField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, upload_to='beneficios/')),
                ('terminos_condiciones', models.TextField(blank=True)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fin', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Beneficio',
                'verbose_name_plural': 'Tipos de Beneficio',
                'db_table': 'tipos_beneficio',
            },
        ),
        migrations.CreateModel(
            name='TipoInsignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('criterios', models.TextField()),
                ('icono', models.ImageField(blank=True, upload_to='insignias/')),
                ('color_hex', models.CharField(default='#1f2937', max_length=7)),
                ('nivel', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('platino', 'Platino'), ('diamante', 'Diamante')], default='bronce', max_length=20)),
                ('puntos_requeridos', models.IntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Insignia',
                'verbose_name_plural': 'Tipos de Insignia',
                'db_table': 'tipos_insignia',
            },
        ),
        migrations.CreateModel(
            name='TipoReconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('criterios', models.TextField()),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('permite_repetir_empleado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Reconocimiento',
                'verbose_name_plural': 'Tipos de Reconocimiento',
                'db_table': 'tipos_reconocimiento',
            },
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('puntos', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
                ('objeto_relacionado_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_relacionado_id', models.UUIDField(blank=True, null=True)),
                ('fecha_obtencion', models.DateTimeField(auto_now_add=True)),
                ('validado', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.tipoactividad')),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historiales de Puntos',
                'db_table': 'historial_puntos',
            },
        ),
        migrations.CreateModel(
            name='CanjeoBeneficio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_canje', models.CharField(max_length=20, unique=True)),
                ('puntos_utilizados', models.IntegerField()),
                ('fecha_canje', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.tipobeneficio')),
            ],
            options={
                'verbose_name': 'Canjeo de Beneficio',
                'verbose_name_plural': 'Canjeos de Beneficio',
                'db_table': 'canjeos_beneficio',
            },
        ),
        migrations.CreateModel(
            name='InsigniaEmpleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True)),
                ('otorgado_automaticamente', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('otorgado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.tipoinsignia')),
            ],
            options={
                'verbose_name': 'Insignia de Empleado',
                'verbose_name_plural': 'Insignias de Empleado',
                'db_table': 'insignias_empleado',
                'unique_together': {('empleado', 'tipo_insignia')},
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('trimestre', models.IntegerField(blank=True, null=True)),
                ('puntuacion_obtenida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('justificacion', models.TextField()),
                ('beneficio_otorgado', models.TextField(blank=True)),
                ('fecha_otorgamiento', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('otorgado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_reconocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recognition.tiporeconocimiento')),
            ],
            options={
                'verbose_name': 'Reconocimiento',
                'verbose_name_plural': 'Reconocimientos',
                'db_table': 'reconocimientos',
                'unique_together': {('tipo_reconocimiento', 'periodo', 'empleado')},
            },
        ),
    ]
