# Generated by Django 5.2.5 on 2025-10-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canjeobeneficio',
            name='fecha_reclamo_programada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
