# Generated by Django 5.2.5 on 2025-11-10 13:06

import custom_storage.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0002_canjeobeneficio_fecha_reclamo_programada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinsignia',
            name='icono',
            field=models.ImageField(blank=True, storage=custom_storage.media.MediaStorage(), upload_to='insignias/'),
        ),
    ]
