# Generated by Django 5.2.5 on 2025-11-10 13:09

import custom_storage.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_alter_tipoinsignia_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipobeneficio',
            name='imagen',
            field=models.ImageField(blank=True, storage=custom_storage.media.MediaStorage(), upload_to='beneficios/'),
        ),
    ]
