# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('obligatoria', models.BooleanField(default=False)),
                ('anonima', models.BooleanField(default=False)),
                ('frecuencia_dias', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Encuesta',
                'verbose_name_plural': 'Tipos de Encuesta',
                'db_table': 'tipos_encuesta',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('instrucciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipo_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.tipoencuesta')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'db_table': 'encuestas',
            },
        ),
        migrations.CreateModel(
            name='EncuestaArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.areaempresa')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
            ],
            options={
                'db_table': 'encuestas_areas',
            },
        ),
        migrations.CreateModel(
            name='EncuestaCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.cargo')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
            ],
            options={
                'db_table': 'encuestas_cargos',
            },
        ),
        migrations.CreateModel(
            name='ParticipacionEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('tiempo_empleado_minutos', models.IntegerField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('porcentaje_completado', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.empleado')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
            ],
            options={
                'verbose_name': 'Participación en Encuesta',
                'verbose_name_plural': 'Participaciones en Encuesta',
                'db_table': 'participaciones_encuesta',
                'unique_together': {('empleado', 'encuesta')},
            },
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('pregunta', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.encuesta')),
                ('tipo_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.tipopregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de Encuesta',
                'verbose_name_plural': 'Preguntas de Encuesta',
                'db_table': 'preguntas_encuesta',
                'unique_together': {('encuesta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='OpcionEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opcion', models.TextField()),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.preguntaencuesta')),
            ],
            options={
                'verbose_name': 'Opción de Encuesta',
                'verbose_name_plural': 'Opciones de Encuesta',
                'db_table': 'opciones_encuesta',
                'unique_together': {('pregunta', 'orden')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('opcion_seleccionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.opcionencuesta')),
                ('participacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.participacionencuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.preguntaencuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Encuesta',
                'verbose_name_plural': 'Respuestas de Encuesta',
                'db_table': 'respuestas_encuesta',
                'unique_together': {('participacion', 'pregunta')},
            },
        ),
    ]
