# Generated by Django 5.2.5 on 2026-08-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='respuestaencuesta',
            unique_together={('participacion', 'pregunta', 'opcion_seleccionada')},
        ),
    ]
