# Generated by Django 5.2.5 on 2025-11-13 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='aprobada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='aspectos_mejora_generados',
            field=models.TextField(blank=True, help_text='Aspectos de mejora generados automáticamente'),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='comentarios_aprobacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='estado_aprobacion',
            field=models.CharField(blank=True, choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('desaprobada', 'Desaprobada'), ('requiere_revision', 'Requiere Revisión')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='recomendacion_continuidad',
            field=models.CharField(blank=True, choices=[('continua', 'Continúa'), ('no_continua', 'No Continúa')], max_length=20, null=True),
        ),
    ]
