# Generated by Django 5.2.5 on 2025-11-20 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_asignacionevaluacion_aprobada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMejoraPredefinido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_mejora', models.TextField(help_text='Plan de mejora generado automáticamente basado en las respuestas')),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('en_seguimiento', 'En Seguimiento'), ('completado', 'Completado'), ('rechazado', 'Rechazado')], default='pendiente_aprobacion', max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_aprobacion', models.TextField(blank=True, help_text='Comentarios del supervisor durante la aprobación')),
                ('comentarios_seguimiento', models.TextField(blank=True, help_text='Comentarios del seguimiento')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_aprobados', to=settings.AUTH_USER_MODEL)),
                ('asignacion_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.asignacionevaluacion')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Mejora Predefinido',
                'verbose_name_plural': 'Planes de Mejora Predefinidos',
                'db_table': 'planes_mejora_predefinidos',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionFinal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('parcialmente_exitoso', 'Parcialmente Exitoso'), ('no_exitoso', 'No Exitoso')], max_length=25)),
                ('conclusion', models.TextField(help_text='Conclusión final del evaluador sobre el plan de mejora')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('evaluado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan_mejora', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_final', to='evaluations.planmejorapredefinido')),
            ],
            options={
                'verbose_name': 'Evaluación Final',
                'verbose_name_plural': 'Evaluaciones Finales',
                'db_table': 'evaluaciones_finales',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoBimensual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_bimestre', models.IntegerField(help_text='1, 2, 3 (primer, segundo, tercer bimestre)')),
                ('fecha_limite', models.DateField(help_text='Fecha límite para completar este seguimiento')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('atrasado', 'Atrasado')], default='pendiente', max_length=15)),
                ('avance_satisfactorio', models.BooleanField(blank=True, help_text='¿El avance es satisfactorio?', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del seguimiento')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan_mejora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='evaluations.planmejorapredefinido')),
            ],
            options={
                'verbose_name': 'Seguimiento Bimensual',
                'verbose_name_plural': 'Seguimientos Bimensuales',
                'db_table': 'seguimientos_bimensuales',
                'ordering': ['plan_mejora', 'numero_bimestre'],
                'unique_together': {('plan_mejora', 'numero_bimestre')},
            },
        ),
    ]
