# Generated by Django 5.2.5 on 2025-11-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_planmejorapredefinido_evaluacionfinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='aceptado_por_empleado',
            field=models.BooleanField(default=False, help_text='Indica si el empleado ha aceptado el plan'),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='fecha_aceptacion_empleado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado aceptó el plan', null=True),
        ),
    ]
