# Generated by Django 5.2.5 on 2025-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_agregar_aceptacion_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionevaluacion',
            name='periodo_evaluacion',
            field=models.CharField(max_length=100),
        ),
    ]
