# Generated by Django 5.2.5 on 2026-03-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_alter_planmejorapredefinido_asignacion_evaluacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='comentarios_decision_rrhh',
            field=models.TextField(blank=True, help_text='Comentarios de RRHH sobre la decisión tomada'),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='decidido_por_rrhh',
            field=models.ForeignKey(blank=True, help_text='Usuario de RRHH que tomó la decisión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisiones_rrhh_planes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='decision_rrhh',
            field=models.CharField(blank=True, choices=[('aprobar_plan_original', 'Aprobar Plan Original'), ('solicitar_nueva_evaluacion', 'Solicitar Nueva Evaluación'), ('modificar_plan', 'Modificar Plan')], help_text='Decisión de RRHH sobre el plan rechazado por el empleado', max_length=30),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='en_revision_rrhh',
            field=models.BooleanField(default=False, help_text='Indica si está en revisión por RRHH tras rechazo del empleado'),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='fecha_decision_rrhh',
            field=models.DateTimeField(blank=True, help_text='Fecha de la decisión de RRHH', null=True),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='fecha_rechazo_empleado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado rechazó el plan', null=True),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='motivo_rechazo_empleado',
            field=models.TextField(blank=True, help_text='Motivo por el cual el empleado rechazó el plan'),
        ),
        migrations.AddField(
            model_name='planmejorapredefinido',
            name='rechazado_por_empleado',
            field=models.BooleanField(default=False, help_text='Indica si el empleado ha rechazado el plan'),
        ),
    ]
