# Generated by Django 5.2.5 on 2026-03-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_agregar_rechazo_plan_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='uso_epp_sst',
            field=models.CharField(blank=True, choices=[('correcto', 'Los usa correctamente y promueve su uso'), ('a_veces', 'A veces no los usa adecuadamente'), ('nunca', 'No los usa o no promueve su uso')], help_text='Observación de SST - No computa en el puntaje de la evaluación', max_length=20, verbose_name='Uso de Elementos de Protección Personal (EPP)'),
        ),
    ]
