# Generated by Django 5.2.5 on 2026-03-06 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0008_agregar_campo_uso_epp_sst'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncargo',
            name='activada_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que activó la evaluación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_cargo_activadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacioncargo',
            name='dias_para_completar',
            field=models.IntegerField(default=30, help_text='Días que tienen los empleados para completar la evaluación'),
        ),
        migrations.AddField(
            model_name='evaluacioncargo',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('activa', 'Activa'), ('finalizada', 'Finalizada')], default='programada', help_text='La evaluación se asigna a empleados solo cuando está Activa', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluacioncargo',
            name='fecha_activacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se activó la evaluación y se asignó a empleados', null=True),
        ),
        migrations.AddField(
            model_name='evaluacioncargo',
            name='fecha_vencimiento_planeada',
            field=models.DateField(blank=True, help_text='Fecha límite para completar la evaluación', null=True),
        ),
    ]
