# Generated by Django 5.2.5 on 2026-03-09 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_agregar_control_activacion_evaluacion_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionfinal',
            name='aceptado_por_empleado',
            field=models.BooleanField(default=False, help_text='Si el empleado aceptó la evaluación final'),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='comentarios_rrhh',
            field=models.TextField(blank=True, default='', help_text='Comentarios de RRHH sobre la resolución'),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='en_revision_rrhh',
            field=models.BooleanField(default=False, help_text='Si está en revisión por Gestión Humana'),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='fecha_aceptacion_empleado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado aceptó', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='fecha_rechazo_empleado',
            field=models.DateTimeField(blank=True, help_text='Fecha en que el empleado rechazó', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='fecha_validacion_rrhh',
            field=models.DateTimeField(blank=True, help_text='Fecha de validación por RRHH', null=True),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='motivo_rechazo_empleado',
            field=models.TextField(blank=True, default='', help_text='Motivo del rechazo por parte del empleado'),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='rechazado_por_empleado',
            field=models.BooleanField(default=False, help_text='Si el empleado rechazó la evaluación final'),
        ),
        migrations.AddField(
            model_name='evaluacionfinal',
            name='validado_por_rrhh',
            field=models.ForeignKey(blank=True, help_text='Usuario de RRHH que validó la evaluación final', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_finales_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evaluacionfinal',
            name='evaluado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_finales_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
