# Generated by Django 5.2.5 on 2026-03-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_evaluacionfinal_aceptado_por_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncargo',
            name='periodo_a_evaluar',
            field=models.CharField(blank=True, help_text='Período a evaluar (ej: 2025, 2025-2026, etc.)', max_length=50),
        ),
    ]
