# Generated by Django 5.2.5 on 2026-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_evaluacioncargo_periodo_a_evaluar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionevaluacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
    ]
