# Generated by Django 5.2.5 on 2026-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_agregar_estado_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionevaluacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('requiere_correccion', 'Requiere Corrección'), ('finalizada', 'Finalizada'), ('vencida', 'Vencida')], default='pendiente', max_length=20),
        ),
    ]
