# Generated by Django 5.2.5 on 2026-05-13 18:10

from django.db import migrations


def actualizar_evaluaciones_desaprobadas(apps, schema_editor):
    """
    Actualiza las evaluaciones que fueron desaprobadas antes de implementar
    el nuevo estado 'requiere_correccion'. Cambia su estado de 'completada'
    a 'requiere_correccion' para que los jefes puedan re-editarlas.
    """
    AsignacionEvaluacion = apps.get_model('evaluations', 'AsignacionEvaluacion')

    # Buscar evaluaciones completadas que fueron desaprobadas
    evaluaciones_desaprobadas = AsignacionEvaluacion.objects.filter(
        estado='completada',
        estado_aprobacion='desaprobada'
    )

    # Contar cuántas se van a actualizar
    total = evaluaciones_desaprobadas.count()

    if total > 0:
        # Actualizar el estado a 'requiere_correccion'
        evaluaciones_desaprobadas.update(estado='requiere_correccion')
        print(f"[OK] Se actualizaron {total} evaluaciones desaprobadas al estado 'requiere_correccion'")
    else:
        print("[OK] No hay evaluaciones desaprobadas que actualizar")


def revertir_actualizacion(apps, schema_editor):
    """
    Revierte los cambios si se hace rollback de la migración.
    Vuelve las evaluaciones con 'requiere_correccion' y 'desaprobada'
    al estado 'completada'.
    """
    AsignacionEvaluacion = apps.get_model('evaluations', 'AsignacionEvaluacion')

    # Buscar evaluaciones que requieren corrección y están desaprobadas
    evaluaciones_a_revertir = AsignacionEvaluacion.objects.filter(
        estado='requiere_correccion',
        estado_aprobacion='desaprobada'
    )

    total = evaluaciones_a_revertir.count()

    if total > 0:
        evaluaciones_a_revertir.update(estado='completada')
        print(f"[OK] Se revirtieron {total} evaluaciones al estado 'completada'")


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0013_agregar_estado_requiere_correccion'),
    ]

    operations = [
        migrations.RunPython(
            actualizar_evaluaciones_desaprobadas,
            reverse_code=revertir_actualizacion
        ),
    ]
