# Generated by Django 5.2.5 on 2026-05-22 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0025_consolidar_estados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooSyncFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False, help_text='Marcar cuando el pull horario reconcilió el cambio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odoo_sync_fallas', to='employees.empleado')),
            ],
            options={
                'db_table': 'odoo_sync_fallas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['resuelta', '-fecha'], name='odoo_sync_f_resuelt_173e8d_idx'), models.Index(fields=['empleado', '-fecha'], name='odoo_sync_f_emplead_baa108_idx')],
            },
        ),
    ]
