# Generated by Django 5.2.5 on 2026-06-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones_odoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odoosyncfalla',
            name='evento',
            field=models.CharField(choices=[('created', 'Creado'), ('updated', 'Actualizado'), ('deleted', 'Eliminado'), ('vacacion', 'Vacación enviada')], max_length=20),
        ),
    ]
