# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Entero'), ('decimal', 'Decimal'), ('boolean', 'Booleano'), ('date', 'Fecha'), ('datetime', 'Fecha y Hora'), ('json', 'JSON')], default='string', max_length=20)),
                ('valor_defecto', models.TextField(blank=True)),
                ('editable_usuario', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'unique_together': {('modulo', 'clave')},
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=50)),
                ('objeto_id', models.UUIDField(blank=True, null=True)),
                ('cambios_realizados', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('metodo_http', models.CharField(blank=True, max_length=10)),
                ('url_accedida', models.CharField(blank=True, max_length=500)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Actividad',
                'verbose_name_plural': 'Logs de Actividad',
                'db_table': 'log_actividades',
                'indexes': [models.Index(fields=['usuario', 'fecha_accion'], name='log_activid_usuario_967d73_idx'), models.Index(fields=['modelo', 'accion'], name='log_activid_modelo_690802_idx')],
            },
        ),
    ]
