# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nivel', models.CharField(max_length=50, unique=True)),
                ('orden', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Escolaridad',
                'verbose_name_plural': 'Escolaridades',
                'db_table': 'escolaridad',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EstadoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permite_acceso_sistema', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado de Empleado',
                'verbose_name_plural': 'Estados de Empleado',
                'db_table': 'estados_empleado',
            },
        ),
        migrations.CreateModel(
            name='HistorialCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('motivo_cambio', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial de Cargo',
                'verbose_name_plural': 'Historiales de Cargo',
                'db_table': 'historial_cargos',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_numero', models.BooleanField(default=True)),
                ('longitud_minima', models.IntegerField(default=8)),
                ('longitud_maxima', models.IntegerField(default=15)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'db_table': 'tipos_documento',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=50)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=15)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
            },
        ),
    ]
