# Generated by Django 5.2 on 2025-07-15 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizational', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.sede'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empleado',
            name='escolaridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.escolaridad'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.estadoempleado'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizational.cargo'),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.tipodocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='historialcargo',
            unique_together={('empleado', 'activo')},
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['numero_documento'], name='empleados_numero__e81b73_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado'], name='empleados_estado__b68771_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['sede'], name='empleados_sede_id_45b4d3_idx'),
        ),
    ]
