# Generated by Django 5.2 on 2025-07-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_cargo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
