# Generated by Django 5.2 on 2025-07-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_departamento_remove_empleado_ciudad_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ciudad_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.ciudad'),
        ),
    ]
