# Generated by Django 5.2 on 2025-07-25 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_empleado_ciudad_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ciudad_nacimiento_text',
        ),
    ]
