# Generated by Django 5.2.5 on 2025-09-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_empleado_ciudad_nacimiento_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='SIN DIRECCIÓN', help_text='Dirección de residencia (debe iniciar con el tipo de vía completo)', max_length=200),
            preserve_default=False,
        ),
    ]
