# Generated by Django 5.2.5 on 2025-11-07 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_empleado_direccion'),
        ('organizational', '0002_cargo_rol_automatico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empleado',
            name='empleados_numero__e81b73_idx',
        ),
        migrations.AlterUniqueTogether(
            name='historialcargo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialcargo',
            name='creado_por',
            field=models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialcargo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['fecha_ingreso'], name='empleados_fecha_i_782325_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado', 'sede'], name='empleados_estado__49cce4_idx'),
        ),
    ]
