# Generated by Django 5.2.5 on 2025-11-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_remove_empleado_empleados_numero__e81b73_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcargo',
            name='activo',
        ),
        migrations.AddField(
            model_name='historialcargo',
            name='activa',
            field=models.BooleanField(default=True),
        ),
    ]
