# Generated by Django 5.2.5 on 2025-11-26 20:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_historialcargo_jefe_directo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada')),
                ('icono', models.CharField(blank=True, help_text='Clase de icono (Font Awesome)', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='Si la categoría está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'marketplace_categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, help_text='Título opcional de la conversación', max_length=200)),
                ('contexto', models.CharField(choices=[('venta', 'Venta'), ('subasta', 'Subasta'), ('regalo', 'Regalo'), ('general', 'General')], default='general', help_text='Contexto de la conversación', max_length=20)),
                ('archivada', models.BooleanField(default=False)),
                ('fecha_ultima_actividad', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='conversaciones', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'messaging_conversaciones',
                'ordering': ['-fecha_ultima_actividad'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('archivos_adjuntos', models.FileField(blank=True, help_text='Archivo adjunto (opcional)', null=True, upload_to='messaging/archivos/')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='employees.conversacion')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'messaging_mensajes',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LecturaConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='employees.conversacion')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_lecturas', to='employees.empleado')),
                ('ultimo_mensaje_leido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.mensaje')),
            ],
            options={
                'verbose_name': 'Lectura de Conversación',
                'verbose_name_plural': 'Lecturas de Conversaciones',
                'db_table': 'messaging_lecturas',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título del producto', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto')),
                ('tipo', models.CharField(choices=[('venta', 'Venta Normal'), ('regalo', 'Regalo'), ('subasta', 'Subasta')], default='venta', help_text='Tipo de oferta', max_length=10)),
                ('precio_inicial', models.DecimalField(blank=True, decimal_places=2, help_text='Precio inicial para venta o valor base para subasta', max_digits=12, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='marketplace/productos/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], default='activo', help_text='Estado actual del producto', max_length=15)),
                ('categoria', models.ForeignKey(help_text='Categoría del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.categoria')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(help_text='Empleado que ofrece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos_creados', to='employees.empleado')),
                ('visible_para', models.ManyToManyField(blank=True, help_text='Empleados que pueden ver este producto (vacío = todos)', related_name='productos_visibles', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'marketplace_productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='producto_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='employees.producto'),
        ),
        migrations.CreateModel(
            name='Regalo',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente aceptación'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('mensaje', models.TextField(blank=True, help_text='Mensaje del donante')),
                ('fecha_ofrecimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_aceptacion', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('donante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_dados', to='employees.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos', to='employees.producto')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_recibidos', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Regalo',
                'verbose_name_plural': 'Regalos',
                'db_table': 'marketplace_regalos',
                'ordering': ['-fecha_ofrecimiento'],
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_actual', models.DecimalField(decimal_places=2, default=0, help_text='Precio de la puja más alta', max_digits=12)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='activa', max_length=15)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(help_text='Fecha y hora de finalización de la subasta')),
                ('incremento_minimo', models.DecimalField(decimal_places=2, default=1000, help_text='Incremento mínimo para nueva puja', max_digits=12)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('ganador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subastas_ganadas', to='employees.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas', to='employees.producto')),
                ('pujador_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subastas_pujadas', to='employees.empleado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subastas_creadas', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Subasta',
                'verbose_name_plural': 'Subastas',
                'db_table': 'marketplace_subastas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PujaSubasta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('es_puja_automatica', models.BooleanField(default=False, help_text='Si es una puja automática del sistema')),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo permitido para pujas automáticas', max_digits=12, null=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('pujador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_pujas', to='employees.empleado')),
                ('subasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='employees.subasta')),
            ],
            options={
                'verbose_name': 'Puja',
                'verbose_name_plural': 'Pujas',
                'db_table': 'marketplace_pujas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_final', models.DecimalField(decimal_places=2, help_text='Precio final acordado', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente_vendedor', 'Pendiente aceptación vendedor'), ('pendiente_comprador', 'Pendiente confirmación comprador'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente_vendedor', max_length=25)),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre la venta')),
                ('calificacion_vendedor', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del vendedor (1-5 estrellas)', null=True)),
                ('calificacion_comprador', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del comprador (1-5 estrellas)', null=True)),
                ('comentario_vendedor', models.TextField(blank=True, help_text='Comentario sobre el comprador')),
                ('comentario_comprador', models.TextField(blank=True, help_text='Comentario sobre el vendedor')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='employees.empleado')),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='employees.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_como_vendedor', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'marketplace_ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'fecha_creacion'], name='messaging_m_convers_f4f0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente'], name='messaging_m_remiten_6258f9_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['leido'], name='messaging_m_leido_acda0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lecturaconversacion',
            unique_together={('conversacion', 'empleado')},
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['vendedor', 'estado'], name='marketplace_vendedo_69b658_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'estado'], name='marketplace_categor_8f922d_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo', 'estado'], name='marketplace_tipo_74fbaa_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['fecha_creacion'], name='marketplace_fecha_c_857573_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_ultima_actividad'], name='messaging_c_fecha_u_427474_idx'),
        ),
        migrations.AddIndex(
            model_name='regalo',
            index=models.Index(fields=['receptor', 'estado'], name='marketplace_recepto_7ce885_idx'),
        ),
        migrations.AddIndex(
            model_name='regalo',
            index=models.Index(fields=['donante'], name='marketplace_donante_97f374_idx'),
        ),
        migrations.AddIndex(
            model_name='subasta',
            index=models.Index(fields=['vendedor', 'estado'], name='marketplace_vendedo_0312dd_idx'),
        ),
        migrations.AddIndex(
            model_name='subasta',
            index=models.Index(fields=['estado', 'fecha_fin'], name='marketplace_estado_c1404d_idx'),
        ),
        migrations.AddIndex(
            model_name='subasta',
            index=models.Index(fields=['pujador_actual'], name='marketplace_pujador_98df4e_idx'),
        ),
        migrations.AddIndex(
            model_name='pujasubasta',
            index=models.Index(fields=['subasta', 'fecha_creacion'], name='marketplace_subasta_905bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='pujasubasta',
            index=models.Index(fields=['pujador'], name='marketplace_pujador_25e0df_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor', 'estado'], name='marketplace_vendedo_d3cf46_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['comprador', 'estado'], name='marketplace_comprad_0ec807_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='marketplace_fecha_v_ad80c2_idx'),
        ),
    ]
