# Generated by Django 5.2.5 on 2025-11-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_add_product_quantity_and_reservations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='reserva_unique_producto_comprador_estado',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='marketplace_product_6da00d_idx',
            old_name='marketplace__product_6789ab_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='marketplace_comprad_eacf28_idx',
            old_name='marketplace__comprad_4567cd_idx',
        ),
        migrations.RenameIndex(
            model_name='reserva',
            new_name='marketplace_fecha_c_587e5a_idx',
            old_name='marketplace__fecha_c_2345ef_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('producto', 'comprador', 'estado')},
        ),
    ]
