# Generated by Django 5.2.5 on 2025-11-28 13:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_remove_reserva_reserva_unique_producto_comprador_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, help_text='Título opcional de la publicación', max_length=200, null=True)),
                ('contenido', models.TextField(help_text='Contenido principal de la publicación')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de fondo opcional (máx 5MB)', null=True, upload_to='publicaciones/%Y/%m/%d/')),
                ('es_anuncio', models.BooleanField(default=False, help_text='¿Es un anuncio (solo admins pueden crear)?')),
                ('es_importante', models.BooleanField(default=False, help_text='¿Es un anuncio importante? (solo si es_anuncio=True)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_eliminacion_automatica', models.DateTimeField(blank=True, help_text='Fecha cuando se eliminará automáticamente (15 días para publicaciones normales)', null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de finalización del anuncio importante', null=True)),
                ('estilos', models.JSONField(blank=True, default=dict, help_text='Estilos CSS: font_size, font_family, text_color, background_opacity')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_publicaciones', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'db_table': 'feed_publicaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenido', models.TextField(help_text='Contenido del comentario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comentarios', to='employees.empleado')),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='employees.publicacion')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'feed_comentarios',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['-fecha_creacion'], name='feed_public_fecha_c_66c684_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['es_anuncio', '-fecha_creacion'], name='feed_public_es_anun_cfc4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['es_importante', '-fecha_creacion'], name='feed_public_es_impo_a784b0_idx'),
        ),
        migrations.AddIndex(
            model_name='publicacion',
            index=models.Index(fields=['fecha_fin'], name='feed_public_fecha_f_b40f98_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['publicacion', 'fecha_creacion'], name='feed_coment_publica_423fc5_idx'),
        ),
    ]
