# Generated by Django 5.2.5 on 2025-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_publicacion_imagen_renderizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='es_rapida',
            field=models.BooleanField(default=False, help_text='¿Es una publicación rápida? (sin editor completo, dura 6 meses)'),
        ),
    ]
