# Generated by Claude 2025-12-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_publicacion_es_rapida'),
    ]

    operations = [
        migrations.AddField(
            model_name='regalo',
            name='confirmado_por_donante',
            field=models.BooleanField(default=False, help_text='Si el donante confirmó la entrega del regalo'),
        ),
    ]
