# Generated by Django 5.2.5 on 2025-12-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0021_regalo_confirmado_por_donante'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, help_text='Fecha de inicio de la publicación (si es nula, se publica inmediatamente)', null=True),
        ),
    ]
