# Generated by Django 5.2.5 on 2025-12-05 18:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_publicacion_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='marketplace/productos/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de fondo opcional (máx 5MB)', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='publicaciones/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='imagen_renderizada',
            field=models.ImageField(blank=True, help_text='Imagen final con texto renderizado', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='anuncios_renderizados/%Y/%m/%d/'),
        ),
    ]
