# Generated by Django 5.2.5 on 2026-02-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0023_alter_producto_imagen_alter_publicacion_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad de unidades solicitadas por el comprador'),
        ),
    ]
