# Generated by Django 5.2.5 on 2026-05-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0025_consolidar_estados_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoMundial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(help_text='Nombre del equipo local', max_length=50)),
                ('equipo_visitante', models.CharField(help_text='Nombre del equipo visitante', max_length=50)),
                ('bandera_local', models.CharField(blank=True, help_text='Emoji de bandera del equipo local', max_length=10)),
                ('bandera_visitante', models.CharField(blank=True, help_text='Emoji de bandera del equipo visitante', max_length=10)),
                ('fecha_hora', models.DateTimeField(help_text='Fecha y hora del partido')),
                ('fase', models.CharField(choices=[('grupos', 'Fase de Grupos'), ('octavos', 'Octavos de Final'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('tercer_lugar', 'Tercer Lugar'), ('final', 'Final')], default='grupos', help_text='Fase del torneo', max_length=20)),
                ('grupo', models.CharField(blank=True, help_text='Grupo (solo para fase de grupos, ej: A, B, C...)', max_length=10)),
                ('estadio', models.CharField(blank=True, help_text='Nombre del estadio', max_length=100)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad sede', max_length=50)),
                ('goles_local', models.IntegerField(blank=True, help_text='Goles del equipo local (resultado real)', null=True)),
                ('goles_visitante', models.IntegerField(blank=True, help_text='Goles del equipo visitante (resultado real)', null=True)),
                ('finalizado', models.BooleanField(default=False, help_text='¿Partido finalizado?')),
                ('api_id', models.CharField(blank=True, help_text='ID del partido en TheSportsDB', max_length=50, null=True, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Partido activo para predicciones?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partido Mundial',
                'verbose_name_plural': 'Partidos Mundiales',
                'db_table': 'polla_partidos',
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='polla_parti_fecha_h_a72682_idx'), models.Index(fields=['fase', 'fecha_hora'], name='polla_parti_fase_a60b6e_idx'), models.Index(fields=['finalizado'], name='polla_parti_finaliz_1e8e99_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrediccionMundial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local_prediccion', models.IntegerField(help_text='Predicción de goles del equipo local')),
                ('goles_visitante_prediccion', models.IntegerField(help_text='Predicción de goles del equipo visitante')),
                ('puntos_ganados', models.IntegerField(default=0, help_text='Puntos obtenidos por esta predicción')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la predicción')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización de la predicción')),
                ('empleado', models.ForeignKey(help_text='Empleado que realiza la predicción', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_mundial', to='employees.empleado')),
                ('partido', models.ForeignKey(help_text='Partido para el cual se hace la predicción', on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='employees.partidomundial')),
            ],
            options={
                'verbose_name': 'Predicción Mundial',
                'verbose_name_plural': 'Predicciones Mundiales',
                'db_table': 'polla_predicciones',
                'ordering': ['-fecha_prediccion'],
                'indexes': [models.Index(fields=['empleado', '-puntos_ganados'], name='polla_predi_emplead_9eda4d_idx'), models.Index(fields=['partido', '-puntos_ganados'], name='polla_predi_partido_f2f7a0_idx')],
                'unique_together': {('empleado', 'partido')},
            },
        ),
    ]
