# Generated by Django 5.2.5 on 2026-05-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0026_partidomundial_prediccionmundial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='acepto_terminos_polla_mundial',
            field=models.BooleanField(default=False, help_text='¿Aceptó términos y condiciones de la Polla Mundial?'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_aceptacion_terminos_polla',
            field=models.DateTimeField(blank=True, help_text='Fecha de aceptación de términos de Polla Mundial', null=True),
        ),
    ]
