# Generated by Django 5.2.5 on 2026-06-12 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0027_empleado_acepto_terminos_polla_mundial_and_more'),
        ('organizational', '0003_centrocosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='centro_costo',
            field=models.ForeignKey(blank=True, help_text='Centro de costo al que pertenece el empleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='organizational.centrocosto'),
        ),
    ]
