# Generated by Django 5.2.5 on 2026-06-12 16:12

import apps.employees.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0028_empleado_centro_costo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('union_libre', 'Unión Libre'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('pareja', 'Pareja'), ('hijo', 'Hijo/a'), ('padre', 'Padre/Madre'), ('hermano', 'Hermano/a'), ('otro', 'Otro')], max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('parentesco', models.CharField(blank=True, help_text="Detalle del parentesco si tipo='otro'", max_length=50)),
                ('convive', models.BooleanField(default=False, help_text='Convive con el empleado')),
                ('dependiente_economico', models.BooleanField(default=False, help_text='Dependiente económico del empleado')),
                ('eps', models.CharField(blank=True, help_text='EPS a la que está afiliado', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='employees.empleado')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.tipodocumento')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'db_table': 'familiares',
                'ordering': ['tipo', 'fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFamiliar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('registro_civil', 'Registro Civil'), ('tarjeta_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cédula de Ciudadanía'), ('certificado_estudio', 'Certificado de Estudio'), ('certificado_eps', 'Certificado EPS'), ('otro', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('archivo', models.FileField(upload_to=apps.employees.models._documento_familiar_upload_path)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Si aplica (ej: certificado de estudio)', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('familiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='employees.familiar')),
            ],
            options={
                'verbose_name': 'Documento de Familiar',
                'verbose_name_plural': 'Documentos de Familiares',
                'db_table': 'documentos_familiar',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='familiar',
            index=models.Index(fields=['empleado', 'tipo'], name='familiares_emplead_cdcef5_idx'),
        ),
    ]
