# Generated by Django 5.2.5 on 2026-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0029_empleado_estado_civil_familiar_documentofamiliar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiar',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el registro está vigente'),
        ),
    ]
