# Generated by Django 5.2.5 on 2026-06-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0030_familiar_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofamiliar',
            name='tipo',
            field=models.CharField(choices=[('registro_civil', 'Registro Civil'), ('tarjeta_identidad', 'Tarjeta de Identidad'), ('cedula', 'Cédula de Ciudadanía'), ('certificado_estudio', 'Certificado de Estudio'), ('certificado_eps', 'Certificado EPS'), ('otro', 'Otro')], max_length=30, verbose_name='Clase de documento'),
        ),
    ]
