# Generated by Django 5.2.5 on 2026-06-18 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0031_alter_documentofamiliar_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudVacacion',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('estado_local', models.CharField(choices=[('borrador', 'Borrador'), ('enviada_pendiente_rrhh', 'Enviada — Pendiente RRHH'), ('rechazada_odoo', 'Rechazada por Odoo'), ('error_envio', 'Error de envío')], default='borrador', max_length=30)),
                ('leave_id_odoo', models.IntegerField(blank=True, help_text='ID de hr.leave devuelto por Odoo', null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_envio_odoo', models.DateTimeField(blank=True, null=True)),
                ('respuesta_odoo', models.JSONField(blank=True, help_text='Respuesta cruda de Odoo (auditoría)', null=True)),
                ('creado_por', models.ForeignKey(help_text='Usuario que creó el registro', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(help_text='Empleado a quien le aplica la vacación', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vacacion', to='employees.empleado')),
                ('jefe_solicitante', models.ForeignKey(blank=True, help_text='Jefe (o staff/RRHH) que solicitó la vacación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_solicitadas', to='employees.empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Vacación',
                'verbose_name_plural': 'Solicitudes de Vacación',
                'db_table': 'solicitudes_vacacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empleado', '-fecha_creacion'], name='solicitudes_emplead_1ceca3_idx'), models.Index(fields=['estado_local'], name='solicitudes_estado__64d92b_idx')],
            },
        ),
    ]
