# Generated by Django 5.2.5 on 2026-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0032_solicitudvacacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudvacacion',
            name='estado_local',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada_pendiente_rrhh', 'Enviada — Pendiente RRHH'), ('rechazada_odoo', 'Rechazada por Odoo (saldo/reglas)'), ('error_envio', 'Error de envío'), ('aprobada_rrhh', 'Aprobada por RRHH'), ('rechazada_rrhh', 'Rechazada por RRHH'), ('cancelada_rrhh', 'Cancelada por RRHH')], default='borrador', max_length=30),
        ),
    ]
