# Generated by Django 5.2.5 on 2026-06-24 11:46

import apps.employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0033_alter_solicitudvacacion_estado_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofamiliar',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=apps.employees.models._documento_familiar_upload_path),
        ),
    ]
