# Generated by Django 5.2.5 on 2026-06-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0034_alter_documentofamiliar_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sexo_biologico',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro / Intersexual'), ('N', 'Prefiero no informar')], help_text='Sirve para reportes legales (PILA/DIAN) y segmentación (madres/padres).', max_length=1, verbose_name='Sexo biológico'),
        ),
    ]
