# Generated by Django 5.2.5 on 2026-06-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0035_empleado_sexo_biologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sexo_biologico',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], help_text='Sirve para reportes legales (PILA/DIAN) y segmentación (madres/padres).', max_length=1, verbose_name='Sexo biológico'),
        ),
    ]
