# Generated by Django 5.2.5 on 2026-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0036_alter_empleado_sexo_biologico'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacacion',
            name='tipo',
            field=models.CharField(
                choices=[('tiempo', 'Tiempo (días libres)'), ('pago_dinero', 'Pagada en dinero')],
                default='tiempo',
                help_text='Tipo de vacación: tiempo (días libres) o pago en dinero',
                max_length=20,
            ),
        ),
    ]
