# Generated by Django 5.2.5 on 2026-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0037_agregar_tipo_solicitud_vacacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='saldo_vacaciones_actualizado',
            field=models.DateTimeField(
                blank=True,
                help_text='Fecha/hora del último update de saldo recibido de Odoo.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='empleado',
            name='saldo_vacaciones_dias',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True,
                help_text='Días de vacaciones disponibles según Odoo (considera tiempo + dinero).',
            ),
        ),
        migrations.AddField(
            model_name='solicitudvacacion',
            name='compensacion_id_odoo',
            field=models.IntegerField(
                blank=True, null=True, unique=True,
                help_text=(
                    'ID de la compensación en Odoo (solo aplica cuando tipo=pago_dinero). '
                    'Clave de upsert para compensaciones — no colisiona con leave_id.'
                ),
            ),
        ),
        migrations.AddField(
            model_name='solicitudvacacion',
            name='dias_compensados',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True,
                help_text=(
                    'Días compensados en dinero (informativo, solo tipo=pago_dinero). '
                    'Puede tener decimales (ej: 7.5).'
                ),
            ),
        ),
        migrations.AddField(
            model_name='solicitudvacacion',
            name='fecha_lote_nomina',
            field=models.DateField(
                blank=True, null=True,
                help_text='Fecha del lote de nómina en que se aplicó la compensación (solo tipo=pago_dinero).',
            ),
        ),
        migrations.AddField(
            model_name='solicitudvacacion',
            name='valor_compensacion',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True,
                help_text='Valor pagado al empleado en pesos (solo tipo=pago_dinero).',
            ),
        ),
        migrations.AlterField(
            model_name='solicitudvacacion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvacacion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvacacion',
            name='leave_id_odoo',
            field=models.IntegerField(
                blank=True, null=True,
                help_text='ID de hr.leave devuelto por Odoo (solo aplica cuando tipo=tiempo)',
            ),
        ),
    ]
