# Generated by Django 5.2.5 on 2026-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0038_compensaciones_dinero_y_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='saldo_vacaciones_fecha_corte',
            field=models.DateField(
                blank=True, null=True,
                help_text='Fecha del corte al que corresponde el saldo (típicamente último día del mes anterior).',
            ),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='saldo_vacaciones_actualizado',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='Fecha/hora en que SIGHU consultó el saldo por última vez.',
            ),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='saldo_vacaciones_dias',
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True,
                help_text='Días de vacaciones disponibles al último corte según Odoo.',
            ),
        ),
    ]
