# Generated by Django 5.2.5 on 2026-07-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0039_saldo_fecha_corte'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudvacacion',
            name='carta_confirmada_hash',
            field=models.CharField(
                blank=True, max_length=64,
                help_text='Hash SHA-256 del consentimiento (empleado_id + solicitud_id + fecha).',
            ),
        ),
        migrations.AddField(
            model_name='solicitudvacacion',
            name='carta_descargada_fecha',
            field=models.DateTimeField(
                blank=True, null=True,
                help_text='Fecha/hora en que el empleado descargó la carta con consentimiento.',
            ),
        ),
    ]
