# Generated by Django 5.2.5 on 2026-07-24 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0040_carta_constancia_descarga'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('fecha', models.DateField(help_text='Fecha del registro (solo días L-V)')),
                ('estado', models.CharField(
                    choices=[
                        ('presente', 'Presente'),
                        ('retardo', 'Retardo'),
                        ('ausente', 'Ausente sin justificar'),
                        ('permiso', 'Permiso remunerado'),
                        ('licencia', 'Licencia no remunerada'),
                        ('incapacidad', 'Incapacidad'),
                        ('en_vacaciones', 'En vacaciones'),
                    ],
                    default='presente', max_length=20,
                )),
                ('motivo', models.TextField(blank=True, help_text='Motivo de la ausencia/permiso (obligatorio si estado != presente)')),
                ('creado_por', models.ForeignKey(
                    help_text='Usuario que creó el registro',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)s_creados',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('empleado', models.ForeignKey(
                    help_text='Empleado al que corresponde el registro',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='asistencias',
                    to='employees.empleado',
                )),
                ('registrado_por', models.ForeignKey(
                    blank=True, null=True,
                    help_text='Jefe que registró la asistencia',
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='asistencias_registradas',
                    to='employees.empleado',
                )),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'db_table': 'asistencia_diaria',
                'ordering': ['-fecha', 'empleado__apellidos'],
                'indexes': [
                    models.Index(fields=['fecha'], name='asistencia__fecha_fbf6cd_idx'),
                    models.Index(fields=['empleado', '-fecha'], name='asistencia__emplead_10cf42_idx'),
                    models.Index(fields=['estado'], name='asistencia__estado_6085a3_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('empleado', 'fecha'), name='unique_asistencia_empleado_fecha'),
                ],
            },
        ),
    ]
