# Generated by Django 5.2.5 on 2026-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0041_asistencia_diaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciadiaria',
            name='estado',
            field=models.CharField(
                choices=[
                    ('presente', 'Presente'),
                    ('retardo', 'Retardo'),
                    ('ausente', 'Ausente sin justificar'),
                    ('permiso', 'Permiso remunerado'),
                    ('permiso_no_remunerado', 'Permiso no remunerado'),
                    ('incapacidad', 'Incapacidad'),
                    ('en_vacaciones', 'En vacaciones'),
                ],
                default='presente', max_length=25,
            ),
        ),
    ]
