# Generated by Django 5.2.5 on 2026-07-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0042_agregar_permiso_no_remunerado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='encargado_asistencia',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Subalterno directo autorizado para registrar el equipo cuando este jefe esté ausente',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reemplaza_a',
                to='employees.empleado',
            ),
        ),
    ]
