# Generated by Django 5.2.5 on 2026-07-27 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_encargado_asistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('fecha', models.DateField(help_text='Fecha en que ocurrió la novedad')),
                ('tipo', models.CharField(
                    choices=[
                        ('hora_extra_diurna', 'Hora extra diurna'),
                        ('hora_extra_nocturna', 'Hora extra nocturna'),
                        ('hora_extra_dominical', 'Hora extra dominical/festivo'),
                        ('recargo_nocturno', 'Recargo nocturno'),
                        ('recargo_dominical', 'Recargo dominical/festivo'),
                        ('vigilancia', 'Vigilancia'),
                    ],
                    max_length=25,
                )),
                ('hora_inicio', models.TimeField(blank=True, null=True, help_text='Hora de inicio (opcional si solo se registra total)')),
                ('hora_fin', models.TimeField(blank=True, null=True, help_text='Hora de fin (opcional si solo se registra total)')),
                ('total_horas', models.DecimalField(decimal_places=2, max_digits=5, help_text='Horas totales de la novedad (ej: 2.50 = 2h 30m)')),
                ('motivo', models.TextField(help_text='Motivo de la novedad (obligatorio)')),
                ('observaciones', models.TextField(blank=True)),
                ('estado_aprobacion', models.CharField(
                    choices=[
                        ('pendiente', 'Pendiente de aprobación'),
                        ('aprobada', 'Aprobada por RRHH'),
                        ('rechazada', 'Rechazada por RRHH'),
                    ],
                    default='pendiente', max_length=15,
                )),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('aprobado_por_rrhh', models.ForeignKey(
                    blank=True, null=True,
                    help_text='Usuario RRHH que aprobó/rechazó',
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='novedades_aprobadas',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('creado_por', models.ForeignKey(
                    help_text='Usuario que creó el registro',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)s_creados',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('empleado', models.ForeignKey(
                    help_text='Empleado al que corresponde la novedad',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='novedades_nomina',
                    to='employees.empleado',
                )),
                ('registrado_por', models.ForeignKey(
                    blank=True, null=True,
                    help_text='Jefe que registró la novedad',
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='novedades_registradas',
                    to='employees.empleado',
                )),
            ],
            options={
                'verbose_name': 'Novedad de nómina',
                'verbose_name_plural': 'Novedades de nómina',
                'db_table': 'novedades_nomina',
                'ordering': ['-fecha', 'empleado__apellidos'],
                'indexes': [
                    models.Index(fields=['empleado', '-fecha'], name='novedades_n_emplead_308798_idx'),
                    models.Index(fields=['fecha'], name='novedades_n_fecha_5b132d_idx'),
                    models.Index(fields=['estado_aprobacion'], name='novedades_n_estado__d425fe_idx'),
                ],
            },
        ),
    ]
