# Generated by Django 5.2.5 on 2026-08-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_novedades_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcargo',
            name='fecha_fin_contrato_aprendizaje',
            field=models.DateField(blank=True, help_text='Solo para cargos de aprendiz SENA. Deja vacío para usar el default de 6 meses desde fecha_inicio.', null=True),
        ),
    ]
