# Generated by Django 5.2.5 on 2026-08-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_historial_cargo_fin_aprendizaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_retiro',
            field=models.DateField(
                blank=True, null=True,
                help_text=(
                    'Último día laborado por el empleado. Se registra al inactivarlo desde '
                    'el sistema; Odoo la usa para generar la liquidación. Se limpia al '
                    'reactivar si aplica.'
                ),
            ),
        ),
    ]
