# Generated by Django 5.2.5 on 2026-08-06 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_tipos_compensacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=200)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('fallos_consecutivos', models.PositiveSmallIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción push',
                'verbose_name_plural': 'Suscripciones push',
                'db_table': 'push_subscriptions',
                'indexes': [models.Index(fields=['usuario', 'activa'], name='push_subscr_usuario_525c1c_idx')],
            },
        ),
    ]
